version: '3'
services:
  application:
    build:
      context: ../..
      dockerfile: dockers/development/Dockerfile
    image: 'minecraft-chat/development:latest'
    container_name: minecraft-chat-development
    volumes:
      - ../..:/usr/src/app
      - ~/.gitconfig:/root/.gitconfig
    ports:
      - '3000:3000'
      - '25565:25565'
    command: sleep infinity 
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: minecraft-chat-database
    ports:
      - '27017:27017'
  minecraft-server:
    image: 'itzg/minecraft-server:latest'
    container_name: minecraft-test-server
    env_file:
      - ../minecraft-server/config.env
    volumes:
      - ../minecraft-server/server.properties:/data/server.properties
    network_mode: "service:application"
    depends_on:
      - application
