version: '3'
services:
  application:
    build:
      context: ../..
      dockerfile: dockers/production/Dockerfile
    image: 'woolninesun/minecraft-chat-production:latest'
    container_name: minecraft-chat-production
    ports:
      - '3000:3000'
      - '25565:25565'
    depends_on:
      - database
  database:
    image: mongo:latest
    container_name: minecraft-chat-database
    ports:
      - '27017:27017'
  minecraft-server:
    build:
      context: ../minecraft-server
      dockerfile: Dockerfile
    image: 'woolninesun/minecraft-test-server:latest'
    container_name: minecraft-test-server
    env_file:
      - ../minecraft-server/config.env
    network_mode: "service:application"
    depends_on:
      - application
