version: '3'
services:
  application:
    build:
      context: ../..
      dockerfile: dockers/production/Dockerfile
    image: 'minecraft-chat/production:latest'
    container_name: minecraft-chat-production
    ports:
      - '3000:3000'
      - '25565:25565'
    networks:
       - minecraft-chat
  minecraft-server:
    image: 'itzg/minecraft-server:latest'
    container_name: minecraft-test-server
    env_file:
      - ../minecraft-server/config.env
    volumes:
      - ../minecraft-server/server.properties:/data/server.properties
    network_mode: "service:application"
    depends_on:
      - application
networks:
  minecraft-chat:
    driver: bridge
